export const rules = [
  {"id": "astra.initiative", "models": "astra"},
  {"id": "astra.follow-through", "models": "astra"},
  {"id": "astra.reviewable-approval", "models": "astra"},
  {"id": "astra.reviewable-approval-warnings", "models": "astra"},
  {"id": "astra.skill-priority", "models": "astra"},
  {"id": "astra.skill-transparency", "models": "astra"},
  {"id": "astra.paragraphs", "models": "astra"},
  {"id": "astra.plain-language", "models": "astra"},
  {"id": "astra.avoid-stock-phrases", "models": "astra"},
  {"id": "astra.avoid-stock-phrases-framing", "models": "astra"},
  {"id": "astra.delegation", "models": "astra", "tool": "subagent"},
  {"id": "astra.legible-messages", "models": "astra"},
  {"id": "astra.testing-meaningful", "models": "astra"},
  {"id": "astra.testing-stop", "models": "astra"},
  {"id": "codex.dedicated-tools", "models": "all"},
  {"id": "codex.line-metadata", "models": "all"},
  {"id": "codex.avoid-loops", "models": "all"},
  {"id": "codex.correctness", "models": "all"},
  {"id": "codex.conventions", "models": "all"},
  {"id": "codex.completeness", "models": "all"},
  {"id": "codex.behavior-tests", "models": "all"},
  {"id": "codex.errors", "models": "all"},
  {"id": "codex.coherent-edits", "models": "all"},
  {"id": "codex.types", "models": "all"},
  {"id": "codex.reuse", "models": "all"},
  {"id": "codex.finish", "models": "all"},
  {"id": "codex.ascii", "models": "all"},
  {"id": "codex.comments", "models": "all"},
  {"id": "codex.editing-tools", "models": "all"},
  {"id": "codex.preserve-work", "models": "all"},
  {"id": "codex.amend", "models": "all"},
  {"id": "codex.unexpected-changes", "models": "all"},
  {"id": "codex.destructive-git", "models": "all"},
  {"id": "codex.plan-skip-simple", "models": "all", "tool": "update_plan"},
  {"id": "codex.plan-multiple-steps", "models": "all", "tool": "update_plan"},
  {"id": "codex.plan-update", "models": "all", "tool": "update_plan"},
  {"id": "codex.plan-deliver", "models": "all", "tool": "update_plan"},
  {"id": "codex.plan-closure", "models": "all", "tool": "update_plan"},
  {"id": "codex.plan-promises", "models": "all", "tool": "update_plan"},
  {"id": "codex.simple-requests", "models": "all"},
  {"id": "codex.reviews", "models": "all"},
  {"id": "codex.frontend-typography", "models": "all"},
  {"id": "codex.frontend-color", "models": "all"},
  {"id": "codex.frontend-motion", "models": "all"},
  {"id": "codex.frontend-background", "models": "all"},
  {"id": "codex.frontend-originality", "models": "all"},
  {"id": "codex.frontend-responsive", "models": "all"},
  {"id": "codex.frontend-complete", "models": "all"},
  {"id": "codex.questions", "models": "all"},
  {"id": "codex.file-dumps", "models": "all"},
  {"id": "codex.same-machine", "models": "all"},
  {"id": "codex.next-steps", "models": "all"},
  {"id": "codex.changes", "models": "all"},
  {"id": "codex.command-output", "models": "all"},
  {"id": "codex.parallel-reads", "models": "all"},
  {"id": "gpt-5.6.stop", "models": "family"},
  {"id": "gpt-5.6.short-answer", "models": "family"},
  {"id": "gpt-5.6.tone", "models": "family"},
  {"id": "gpt-5.6.preserve-artifact", "models": "family"},
  {"id": "gpt-5.6.scope", "models": "family"},
  {"id": "gpt-5.6.prerequisites", "models": "family"},
  {"id": "gpt-5.6.retrieval-budget", "models": "family"},
  {"id": "gpt-5.6.updates", "models": "family"},
  {"id": "gpt-5.6.validation", "models": "family"},
  {"id": "gpt-5.6.citations", "models": "family"},
  {"id": "gpt-5.6.frontend", "models": "family"},
  {"id": "astra.updates", "models": "astra"},
  {"id": "gpt-5.6.retrieval-fallback", "models": "family"},
  {"id": "gpt-5.6.visual-validation", "models": "family"},
  {"id": "gpt-5.6.plan-content", "models": "family"},
] as const;
